language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: travis-heroku-2carlos
  on: master
  skip_cleanup: true
  api_key:
    secure: JwLQ+jwv6BiUByfJwXQsCUNsu3iN9ve7AfYTTbzEQxyypXaDZ33xdtvJc1Pn7652WWViljCFY6ejKDB0mZzqLEmo0Gh6D1yk3hi0GzEFF44hHdEZFvSRabpqdyNkNiJhbXOV2SjutS8oucUF68wskcVBQaFZKlbA6+eMq27ZgKLBxp092ybUCF5v7YGN2XqRFoTHs5Z+PWQwR6jt1v2sLO89Y2da8nW7/8SbnAI6EAjew0Ks9DZLxdCwIZPQyjVkhcSG1PB6h+/GQ+eXa2+PhvhkxIx4hPTKXaL7WvzOhHu5ml1/Cv2KFrETCHLC98Mf8dQRrLSJZHPlaxTMLwjHhIVC7A7Ez/0QLwslMwRqnNJpNj5w2ANw6lVIKkZhViVYxGbONTmgdxc1Rl9VRtKBXhBG0CqP/JDH4skplcExk8mtVIs6jPubydPQKAl5znSZdcSya7WDY1oRJtbYvrNqW04MZHbp/c2tkoMngetpizp0bNPJR+ItNH6dfr8Ve7P7EXJcyoFzldGbOek0McxJD/F60d/tnKyEzM6tf7t3uYu0Axc3JosKmJt2QqeK/D6FXb+TdGJTijGo4yPXLEVKCYXYhn9upO9K1xKdmFwl6kxXcKySBPUyO+51dwBJCyNVaflPIUG7oRUrZMcgkTc0ttafI6cfSqbh1IajvKf8JBk=
